services:
  # Executar per produccio: docker compose up --build
  # Executar per desenvolupament: docker compose up <- Sense --build!
  # Recorda crear un venv i instalar els programes per l'autocompletat de l'editor!

  app:
    image: jplanelles-ultra-server:v1
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT:-8002}:8002"
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./src:/app:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: docker-compose.yaml
        - action: rebuild
          path: .env

  postgres:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
